version: 2

sources:
  - name: raw
    tables:
      - name: matches

models:
  - name: stg_matches
    columns:
      - name: match_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - not_null
  - name: dim_teams
    columns:
      - name: team_id
        tests:
          - unique
          - not_null
      - name: team_name
        tests:
          - not_null
      - name: team_shortname
        tests:
          - not_null